# sql 보기
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

logging.level:
    org.hibernate:
      sql: debug
#      type.descriptor.sql: trace # sql의 데이터까지 보이게

server:
  error:
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: on_param  # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated

jwt:
  issuer: petmeetingservice
  secret_key: afd3ad5jf6i23FA89S9DCZ0Xa12sd3qbzxf56Sadvjoupiuy7D5A4F32Zcv14xxvbZ34X32v67QA234d38HG56FbxfDJvcxZFADFzxCV1321
  access_expiration_ms: 3600000
  refresh_expiration_ms: 2592000000

kakao:
  admin_key: bef57d6c185d96c914e88393686973b1
  content_type: application/x-www-form-urlencoded;charset=utf-8
  cid: TC0ONETIME